version: '3'
services:
  pessoas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pessoas
    image: pessoas:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '8080:8080'
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./src/main/resources/db/changelog/changes/1.0.0.0_create_tables_person_and_address.sql:/docker-entrypoint-initdb.d/1.0.0.0_create_tables_person_and_address.sql
      - ./src/main/resources/scripts/initial-data-insert.sql:/docker-entrypoint-initdb.d/initial-data-insert.sql