version: '3'
services:
  pessoas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pessoas
    image: pessoas:latest
    environment:
      POSTGRES_URL:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '8080:8080'
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    expose:
      - '5432'